### ISSUE TITLE
Can't resolve 'framer-motion'

### ISSUE THREAD

**Issue by doliG** [ilyxium/eth-nextjs-boilerplate#1]
Hey,

I'm using your project for a hackathon. Btw thanks :)

Just run into a little problem after installation. To reproduce, clone the repo, install deps with yarn, and then run the project.

```sh
$ yarn dev
yarn run v1.22.10
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - ./node_modules/@chakra-ui/checkbox/dist/chakra-ui-checkbox.esm.js:7:0
Module not found: Can't resolve 'framer-motion'
```

Solved after `yarn add framer-motion`, I think it's a typo in `package.json` 🤔

**Comment by ilyxium** [comment]
Hey, should be fixed now. Thanks for pointing this out
